resources:
  repositories:
  - repository: xxx
    type: githubenterprise
    endpoint: GithubEnterprise
    name: commercial-pc-software/xxx    
    ref: kp/yyy
 
variables:
- group: ZTA
 
trigger: none
 
 
jobs:
- template: pipeline-dispatcher.yml
  parameters:
    serialNumber: "123"
    agentName: 'ZTA_Agent_74'
    pool: "$(poolName)"
    rootId: ''
    componentLocation: '' #'\\\\houcomfile02.auth.hpicorp.net\\PreRelease\\Manageability\\HPIA\\ImagePal-5.1.0.1'
    testExecutionType: 'Azure'
    testCases:
      #Azure
    - "SFT\\HIA\\1_4_ValidateHPSignatureForHPImageAssistantDll"