trigger:
- main

pool:
  name: 'Reboot-Automation'  # Replace with the name of your self-hosted agent pool

variables:
  ip_address: '192.168.1.14'
  system_check_script: 'check_system_status.py'

jobs:
- job: CheckSystemStatus
  displayName: 'Check System Online/Offline Status'
  steps:
  - script: |
      python $(system_check_script)
    displayName: 'Run System Status Check Script'
    name: CheckInitialStatus

  - script: |
      echo "System is online and not rebooting. Proceeding with initial tests..."
      # Add commands to run your initial test cases here.
    displayName: 'Run Initial Tests'
    condition: and(succeeded(), eq(variables['SystemStatus'], 'online'))

  - script: |
      echo "System is either offline or rebooting. Waiting for it to come back online..."
      while ! python -c 'import subprocess, platform, time; from check_system_status import is_system_online, is_system_rebooting; ip_address="$(ip_address)"; print(is_system_online(ip_address) and not is_system_rebooting())'; do
        echo "System is still offline or rebooting. Checking again in 30 seconds..."
        sleep 30
      done
      echo "System is back online. Proceeding with initial tests..."
      # Add commands to run your initial test cases here.
    displayName: 'Wait for System and Run Initial Tests'
    condition: and(succeeded(), eq(variables['SystemStatus'], 'offline'))

  - script: |
      echo "Running system online/offline check during test execution..."
      while ! python -c 'import subprocess, platform, time; from check_system_status import is_system_online, is_system_rebooting; ip_address="$(ip_address)"; print(is_system_online(ip_address) and not is_system_rebooting())'; do
        echo "System went offline or is rebooting. Waiting for it to come back online..."
        sleep 30
      done
      echo "System is back online. Resuming tests..."
      # Add commands to run the remaining test cases here.
    displayName: 'Check System During Tests'
    condition: always()

  - script: |
      echo "Running remaining test cases..."
      # Add commands to run the remaining test cases here.
    displayName: 'Run Remaining Tests'
    condition: always()
