trigger:
- main

pool:
  name: 'Reboot-Automation'  # Replace with the name of your self-hosted agent pool
 

variables:
  ip_address: '192.168.1.14'
  system_check_script: 'check_system_status.py'

jobs:
- job: CheckSystemStatus
  displayName: 'Check System Online/Offline Status'
  steps:
  - script: |
      python $(system_check_script)
    displayName: 'Run System Status Check Script'

  - script: |
      echo "System is online and not rebooting. Proceeding with tests..."
      # Add commands to run your test cases here.
    displayName: 'Run Tests'
    condition: and(succeeded(), eq(variables['SystemStatus'], 'online'))

  - script: |
      echo "System is either offline or rebooting. Waiting for it to come back online..."
      while ! python -c 'import subprocess, platform, time; from check_system_status import is_system_online, is_system_rebooting; ip_address="$(ip_address)"; print(is_system_online(ip_address) and not is_system_rebooting())'; do
        echo "System is still offline or rebooting. Checking again in 30 seconds..."
        sleep 30
      done
      echo "System is back online. Proceeding with tests..."
      # Add commands to run your test cases here.
    displayName: 'Wait for System and Run Tests'
    condition: and(succeeded(), eq(variables['SystemStatus'], 'offline'))
